First integration tests #LSC-97
neutron-org/neutron-integration-tests pull request #1
Opened 2022-07-22 07:29 UTC by ratik

It a starting point for integration testing of Neutron network and contracts:
Simple test - basic tests, contract upload, interchain transfer
Interchain txs - interchain txs contract, interchain delegation

2022-08-10 13:24 UTC, foxpy commented on README.md
> +**Note: it is recommended to clear env with `make restart` before each run to reset the state.**
`make restart`? neutron's Makefile doesn't have rules for `restart` target, and this repo doesn't even have any Makefile in a first place, so please clarify.

2022-08-10 13:37 UTC, ratik commented on README.md
> +**Note: it is recommended to clear env with `make restart` before each run to reset the state.**
thanks 👍

2022-08-10 13:52 UTC, sotnikov-s commented on README.md
> +cp -r ./../neuton-contracts/artifacts ./contracts
typo: neuton -> neut**r**on

2022-08-10 17:03 UTC, oopcode submitted a review, later dismissed

2022-08-11 08:13 UTC, sotnikov-s commented on src/testcases/simple.test.ts
> +      expect(res).not.toEqual('');
you're checking the tx hash not to be empty here. what's the point?

2022-08-11 08:14 UTC, sotnikov-s commented on src/helpers/cosmos.ts
> +        `broadcast error: ${JSON.stringify(res.data?.tx_response)}`,
this doesn't seem to work properly: tested with negative amount and didn't get the pretty string
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/34917380/184091575-51de0c1d-029c-4716-9429-2ad8719562dd.png">

2022-08-12 07:32 UTC, ratik commented on src/helpers/cosmos.ts
> +        `broadcast error: ${JSON.stringify(res.data?.tx_response)}`,
I've replaced with `raw_log` here but I'm sure we shouldn't parse it to get it even prettier

2022-08-15 10:27 UTC, foxpy commented on src/testcases/interchaintx.test.ts
> +      codeId = await cm.storeWasm('neutron_interchain_txs.wasm');
some nstructions on where to get this contract from would be really helpful

2022-08-15 11:40 UTC, ratik commented on src/testcases/interchaintx.test.ts
> +      codeId = await cm.storeWasm('neutron_interchain_txs.wasm');
https://github.com/neutron-org/neutron-contracts/pull/3
but this one is already updated to a new version so the test is kinda outdated, we agreed that Dmitriy will fix/finalize this test to fit new contract version

2022-08-15 11:42 UTC, foxpy commented on src/testcases/interchaintx.test.ts
> +      codeId = await cm.storeWasm('neutron_interchain_txs.wasm');
So, this entire test should fail and that's okay for the time being, right?

2022-08-15 11:43 UTC, ratik commented on src/testcases/interchaintx.test.ts
> +      codeId = await cm.storeWasm('neutron_interchain_txs.wasm');
yep

2022-08-16 09:39 UTC, foxpy commented on .vscode/launch.json
> +    ]
Wait, is it actually used for something? I don't see how Chrome could be useful with these tests.

2022-08-16 09:42 UTC, foxpy requested changes

2022-08-16 09:42 UTC, foxpy commented on README.md
> +NO_DOCKER
Please add `BLOCK_TIME` here as well. Also a little bit of documentation for these variables wouldn't hurt.

2022-08-16 09:46 UTC, foxpy commented on src/helpers/cosmos.ts
> +    return res?.tx_response.txhash;
I don't really understand what's the point of returning just a hash, when you can return a complete tx response, e.g. like I am doing it here: https://github.com/neutron-org/neutron-integration-tests/blob/dc771f89afb06c59d3956dacc142ad667529c8b3/src/helpers/cosmos.ts#L170-L184

What do you think?

2022-08-16 09:47 UTC, foxpy commented on src/helpers/cosmos.ts
> +    return res?.tx_response.txhash;
Ooops, I have linked a wrong function here, but, anyway, both `executeContract` and `msgSend` could return tx response instead of just a hash.

2022-08-16 09:49 UTC, foxpy commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
We have both `package-lock.json` and `yarn.lock`. I am not familiar with JS toolchains at all, hence I am asking a question, is it okay to have these two lock files at the same time? Looks weird.

2022-08-16 10:10 UTC, foxpy approved these changes

2022-08-16 12:36 UTC, sotnikov-s commented on src/testcases/simple.test.ts
> +            amount: '1000',
could you please add a comment here that the contract's innards the sending sum gets tripled, otherwise it's not clear why we send 1000 and expect 3000

2022-08-17 04:59 UTC, foxpy commented on src/testcases/simple.test.ts
> +            amount: '1000',
also specifying a reason for this multiplication wouldn't hurt

2022-08-17 10:24 UTC, ratik commented on src/testcases/simple.test.ts
> +            amount: '1000',
added comment in `check wallet balance` section

2022-08-17 10:26 UTC, sotnikov-s submitted a review, later dismissed

2022-08-17 10:28 UTC, foxpy approved these changes

2022-08-18 13:28 UTC, NeverHappened reviewed
I feel the setup for tests can be more clear, but cannot suggest good solution to it

2022-08-18 13:28 UTC, NeverHappened commented on README.md
> +#### 4. Environment variables you can redefine
Maybe do smth similar as in other repos? Add description for variables at least

2022-08-18 13:28 UTC, NeverHappened commented on src/helpers/cosmos.ts
> +export class CosmosWrapper {
I think name is not clear enough, but cannot imagine a good name

2022-08-18 13:28 UTC, NeverHappened commented on src/testcases/common_localcosmosnet.ts
> +  sdk_1: cosmosclient.CosmosSDK;
Javascript uses camelcase, so I think it should be `sdk1` and `sdk2`

2022-08-18 16:14 UTC, pr0n00gler submitted a review, later dismissed

2022-08-18 16:44 UTC, foxpy commented on src/helpers/cosmos.ts
> +export class CosmosWrapper {
`CosmosClientWrapper`, if you want to be extra verbose? I approve both versions

2022-08-19 06:18 UTC, ratik commented on src/helpers/cosmos.ts
> +export class CosmosWrapper {
hm the name looks ok for me bc it's just a wrapper for cosmos lib

2022-08-19 07:37 UTC, foxpy submitted a review, later dismissed

2022-08-19 07:51 UTC, pr0n00gler approved these changes

2022-08-19 08:38 UTC, NeverHappened approved these changes

2022-08-19 08:40 UTC, sotnikov-s submitted a review, later dismissed

2022-08-19 09:05 UTC, swelf19 approved these changes

2022-08-19 09:05 UTC, swelf19 commented on src/testcases/simple.test.ts
> +        { amount: '10000', denom: 'stake' },
we send a DENOM=process.env.DENOM || 'stake';
and check only 'stake', should be updated i believe

2022-08-19 09:13 UTC, swelf19 approved these changes

2022-08-19 09:16 UTC, NeverHappened approved these changes

2022-08-19 09:16 UTC, foxpy commented
![image](https://user-images.githubusercontent.com/24505352/185587120-9f163221-8181-4f98-bffc-85c14ed411fa.png)
Oh well…

2022-08-19 10:24 UTC, ratik commented
> ![image](https://user-images.githubusercontent.com/24505352/185587120-9f163221-8181-4f98-bffc-85c14ed411fa.png) Oh well…

I haven't touched interchaintxs test bc Dima is updating it

2022-08-19 13:57 UTC, foxpy approved these changes

2022-08-19 13:57 UTC, merged