fix: reserve to treasury
neutron-org/neutron-integration-tests pull request #141
Opened 2023-04-21 19:08 UTC by oopcode

2023-04-26 10:14 UTC, swelf19 commented
https://github.com/neutron-org/neutron-tests/actions/runs/4807112668

2023-04-27 10:19 UTC, sotnikov-s requested changes

2023-04-27 10:19 UTC, sotnikov-s commented on src/testcases/parallel/dao_assert.test.ts
>      test('Reserve is correct', async () => {
**Reserve** is correct -> **Treasury** is correct

2023-04-27 10:19 UTC, sotnikov-s commented on src/testcases/parallel/dao_assert.test.ts
>      test('Reserve hash assert', async () => {
**Reserve** hash assert -> **Treasury** hash assert

2023-04-27 10:34 UTC, sotnikov-s approved these changes

2023-04-27 10:36 UTC, quasisamurai approved these changes

2023-04-27 10:40 UTC, swelf19 approved these changes

2023-04-27 10:45 UTC, merged