[NTRN-483] feat: proper vesting for generator
neutron-org/neutron-integration-tests pull request #165
Opened 2023-06-05 18:36 UTC by sotnikov-s

**task:** https://p2pvalidator.atlassian.net/browse/NTRN-483

2023-06-05 19:22 UTC, sotnikov-s commented
https://github.com/neutron-org/neutron-tests/actions/runs/5180682250

2023-06-06 07:20 UTC, sotnikov-s commented
https://github.com/neutron-org/neutron-tests/actions/runs/5185323749

2023-06-07 09:08 UTC, foxpy requested changes

2023-06-07 09:08 UTC, foxpy commented on src/helpers/tge.ts
> +const GENERATOR_REWARDS_PER_BLOCK = 500;
I think it would be better to follow the flow of `Tge` class and define these constants as class fields.
This way class user could customize them before calling all the `deployX()` functions.

2023-06-07 13:41 UTC, swelf19 submitted a review, later dismissed

2023-06-08 07:25 UTC, sotnikov-s commented on src/helpers/tokenfactory.ts
> +  const msgCreateDenom = new osmosis.tokenfactory.v1beta1.MsgMint({
ty, fixed

2023-06-08 07:25 UTC, sotnikov-s commented on src/helpers/tge.ts
> +const GENERATOR_REWARDS_PER_BLOCK = 500;
goot idea. dona

2023-06-08 08:20 UTC, sotnikov-s commented
https://github.com/neutron-org/neutron-tests/actions/runs/5208581266

2023-06-08 09:09 UTC, merged