Added warning re:docker-compose to readme
neutron-org/neutron-integration-tests pull request #17
Opened 2022-09-20 11:20 UTC by oldremez

2022-09-20 11:24 UTC, ratik submitted a review, later dismissed

2022-09-20 11:26 UTC, foxpy requested changes

2022-09-20 11:26 UTC, foxpy commented on README.md
> +make stop-cosmopark
It is enough to do just this:

```suggestion
docker-compose build
```

2022-09-20 11:26 UTC, foxpy commented on README.md
> +outdated version of code if you changed something. To rebuild the images from scratch, do the following:
You are referring to user as "one" and "you" in a single sentence.

2022-10-15 17:38 UTC, foxpy submitted a review, later dismissed

2022-10-17 06:52 UTC, pr0n00gler submitted a review, later dismissed

2022-10-17 07:42 UTC, foxpy commented
CC @oldremez conflicts :ghost:

2022-10-18 14:32 UTC, oopcode approved these changes

2022-10-18 14:33 UTC, merged