Feat/admin module sdk47
neutron-org/neutron-integration-tests pull request #196
Opened 2023-08-25 09:42 UTC by quasisamurai

2023-08-25 11:05 UTC, pr0n00gler requested changes
Also attach a successful testrun after the fix

2023-08-25 11:05 UTC, pr0n00gler commented on src/testcases/parallel/governance.test.ts
Please add a tests to check non-whitelisted message will not be executed in proposal

2023-08-30 15:02 UTC, sotnikov-s commented on src/testcases/parallel/governance.test.ts
is it possible to add more tests around authority/signers logic?

2023-09-05 16:21 UTC, sotnikov-s approved these changes

2023-09-06 16:07 UTC, quasisamurai commented
https://github.com/neutron-org/neutron-tests/actions/runs/6097481262/job/16550121022

2023-09-07 11:38 UTC, merged