feat: save failed result #ntrn-80
neutron-org/neutron-integration-tests pull request #198
Opened 2023-08-29 10:23 UTC by NeverHappened

https://hadronlabs.atlassian.net/browse/NTRN-80

2023-08-29 13:59 UTC, NeverHappened commented
https://github.com/neutron-org/neutron-tests/actions/runs/6013284667

2023-10-11 08:52 UTC, sotnikov-s requested changes

2023-10-11 08:52 UTC, sotnikov-s commented on src/testcases/parallel/subdao.test.ts
> +      neutronChain.blockWaiter.waitBlocks(2);
forgotten `await`

2023-10-11 08:52 UTC, sotnikov-s commented on src/testcases/parallel/subdao.test.ts
> +    test('proposal timelock 3', async () => {
please add a meaningful test case name

2023-10-11 08:52 UTC, sotnikov-s commented on src/testcases/parallel/subdao.test.ts
> +      // timelocked proposal execution failed due to invalid param value
due to invalid param value  -> due to insufficient funds?

2023-10-11 10:36 UTC, sotnikov-s approved these changes

2023-10-12 12:25 UTC, pr0n00gler commented
Merged in https://github.com/neutron-org/neutron-integration-tests/pull/220

2023-10-12 12:25 UTC, closed without merging