wip
neutron-org/neutron-integration-tests pull request #2
Opened 2022-08-10 13:19 UTC by foxpy

2022-08-11 07:46 UTC, sotnikov-s commented on src/testcases/interchain_kv_query.test.ts
> +      //      are always zero. Is it okay?
afaik it's not for the balance query. it would be ok if you used tx query cuz we don't submit the tx query results, but for this one it should have values there. @pr0n00gler am I right?

2022-08-11 07:50 UTC, pr0n00gler commented on src/testcases/interchain_kv_query.test.ts
> +      //      are always zero. Is it okay?
Yes, zero values in this case are not okay

2022-08-11 10:43 UTC, sotnikov-s commented on src/testcases/interchain_kv_query.test.ts
> +      //      are always zero. Is it okay?
ah, wait, we're here in the block where we registered the query, aren't we? if so, zeroes are ok because update period is 5 and the query hasn't run, yet

2022-08-19 05:02 UTC, foxpy commented on src/testcases/interchain_kv_query.test.ts
> +      //      are always zero. Is it okay?
yep, values get updated after query results are submitted, and now I test this behaviour correctly

2022-08-23 08:42 UTC, sotnikov-s commented on src/testcases/interchain_kv_query.test.ts
> +    // TODO: What about checking "kv_keys", too?
if it's not too complicated, you can do so. otherwise I think it's out of scope of this test cuz it's mostly the neutron sdk helper's + contract's logic and it should be tested in corresponding unit tests

2022-08-23 08:42 UTC, sotnikov-s commented on src/testcases/interchain_kv_query.test.ts
> +        testState.wallets.demo2.address.toAccAddress(),
you've make a sending of 9000 on behalf of `cm[2]`, but then you check whether `testState.wallets.demo2.address.toAccAddress()` equals to query1 result. I don't like two things here:
1. the `testState.wallets.demo2.address.toAccAddress()` doesn't explicitly say that we're checking the cm[2]'s account. I think using `cm2.wallet.address.toString()` would be more clear here;
2. I'd like to see exact values here, like we had 15000 on the balance before, and we've just sent 9000, so we expect it to be 6000. otherwise a mistake can elude you

2022-08-23 08:42 UTC, sotnikov-s commented on src/testcases/interchain_kv_query.test.ts
> +    //       because we only have one node per network in cosmopark
are you planning to do it in this task's scope?

2022-08-23 08:42 UTC, sotnikov-s commented on src/testcases/interchain_kv_query.test.ts
> +    test('perform icq #4: transfers', async () => {
you were supposed to implement kv tests, but this one is a tx test, and the tx queries are covered with tests by me in another file

2022-08-23 08:51 UTC, sotnikov-s commented on src/testcases/interchain_kv_query.test.ts
> +describe('Neutron / Interchain KV Query', () => {
a couple of things that should be tested in additional:
- the contract swallows sudo calls (make changes to the contract's code and add state changing logic to sudo calls, also add a query msg for the contract to read the state. please refer this storage entity usage https://github.com/neutron-org/neutron-contracts/blob/main/contracts/neutron_interchain_queries/src/state.rs#L7);
- with AllowKVCallbacks=false make sure the contract's state hasn't changed;
- getting a query result by a user different from the query owner (optional).

2022-08-23 09:17 UTC, foxpy commented on src/testcases/interchain_kv_query.test.ts
> +        testState.wallets.demo2.address.toAccAddress(),
I agree with point 1, I will fix it.

Point 2 doesn't make much sense for me, since I am testing interchain queries, and I trust ordinary queries to do that. If I cannot trust ordinary queries, then we have bigger problems. Oh, and by the way, your math misses transaction fee, which complicates things a little.

Anyway, I will fix point 1 and, if you ask me again, I will fix point 2 as well.

2022-08-23 09:27 UTC, foxpy commented on src/testcases/interchain_kv_query.test.ts
> +    //       because we only have one node per network in cosmopark
Definitely not. I am just leaving this TODO for future generations to care about.

2022-08-23 09:29 UTC, foxpy commented on src/testcases/interchain_kv_query.test.ts
> +    test('perform icq #4: transfers', async () => {
I agree, but I am not sure if I can do anything about it right now:

https://github.com/neutron-org/neutron-contracts/blob/dd671c5871686cb971a303cfdd0482bef0900065/contracts/neutron_interchain_queries/src/contract.rs#L253-L272

2022-08-23 09:34 UTC, sotnikov-s commented on src/testcases/interchain_kv_query.test.ts
> +        testState.wallets.demo2.address.toAccAddress(),
what I meant and what I wanted to point out is that the validateQuery funcs accept implicit parameters, and if you make a single mistake e.g. pass a wrong address or query there (and there is a lot of addresses and queries and other entities in the code with these index digits etc. which makes it easy to make such a mistake) you will not notice an error. roughly, these funcs actually check whether icq results are same as bank/delegation call results, not whether query result has been updated as you expect

if it still pointless to you, please, don't bother yourself with this and leave as it is. it's just the way I'd like it to be, but it doesn't have to be so

2022-08-23 09:37 UTC, sotnikov-s commented on src/testcases/interchain_kv_query.test.ts
> +    test('perform icq #4: transfers', async () => {
why not? because of something that @pr0n00gler is supposed to change? is it still relevant?

2022-08-23 09:39 UTC, sotnikov-s commented on src/testcases/interchain_kv_query.test.ts
> +    //       because we only have one node per network in cosmopark
could you please elaborate? is it too hard or too premature or what's the reason of not doing it?

2022-08-23 09:47 UTC, foxpy commented on src/testcases/interchain_kv_query.test.ts
> +        testState.wallets.demo2.address.toAccAddress(),
actually I would like to eventually refactor the whole test suite to make it more readable

talking about easy to make mistakes, I could check that `cm[2].wallet`'s balance has decreased during a test, what do you think about it?

2022-08-23 09:47 UTC, foxpy commented on src/testcases/interchain_kv_query.test.ts
> +    //       because we only have one node per network in cosmopark
That's way outside of scope of my task, but I will do that if necessary.

2022-08-23 09:49 UTC, foxpy commented on src/testcases/interchain_kv_query.test.ts
> +    test('perform icq #4: transfers', async () => {
actually I am not even sure. I didn't think I should even touch this code on behalf of my task. or should I actually?

2022-08-23 10:00 UTC, foxpy commented on src/testcases/interchain_kv_query.test.ts
> +describe('Neutron / Interchain KV Query', () => {
> the contract swallows sudo calls (make changes to the contract's code and add state changing logic to sudo calls)

I guess I am already doing it?

> AllowKVCallbacks=false

I will have to toggle this setting and restart cosmopark to do that.

> getting a query result by a user different from the query owner

Aren't queries just available to everyone? I am not even using any user account to perform a query.

Sorry for all these questions, I am just not 100% sure what do you mean

2022-08-23 10:08 UTC, sotnikov-s commented on src/testcases/interchain_kv_query.test.ts
> +        testState.wallets.demo2.address.toAccAddress(),
you can take a glance at my code in the neighbour PR, probably it can give you a hint on it

2022-08-23 10:09 UTC, foxpy commented on src/testcases/interchain_kv_query.test.ts
> +        testState.wallets.demo2.address.toAccAddress(),
has been planning to do that anyway :')

2022-08-23 10:09 UTC, sotnikov-s commented on src/testcases/interchain_kv_query.test.ts
> +    test('perform icq #4: transfers', async () => {
this is exactly what I did to make my contracts testable by callbacks. remember we had a discussion about where to place the contract — in tests repo or in neutron-contracts one? the discussion took place when I was working on that contract modification

2022-08-23 10:13 UTC, sotnikov-s commented on src/testcases/interchain_kv_query.test.ts
> +describe('Neutron / Interchain KV Query', () => {
> Sorry for all these questions, I am just not 100% sure what do you mean

it's totally okay cuz the topic is discussable

> I guess I am already doing it?

you mean the check in the tx query test? you need also to test kv callbacks, and to do so you should modify the contract that helps you in tests (the neutron_interchain_queries one) as I've written above in this thread

2022-08-23 10:26 UTC, foxpy commented on src/testcases/interchain_kv_query.test.ts
> +    // TODO: What about checking "kv_keys", too?
yea it is way out of scope

2022-08-25 10:49 UTC, ratik commented on src/testcases/interchain_kv_query.test.ts
> +  numAttempts?: number,
```suggestion
  numAttempts = 20,
```

2022-08-25 10:51 UTC, ratik commented on src/testcases/interchain_kv_query.test.ts
> +describe('Neutron / Interchain KV Query', () => {
I think implementing test that require restart of cosmopark with specific parameters looks at least like a separate task

2022-08-25 10:58 UTC, ratik commented on src/testcases/interchain_kv_query.test.ts
> +      // XXX: I could actually check that "key" is correctly derived from contractAddress,
not a blocker but you can actually, and we have this lib in yarn.lock https://github.com/neutron-org/neutron-integration-tests/blob/master/yarn.lock#L1521

2022-08-25 11:00 UTC, ratik commented on src/testcases/interchain_kv_query.test.ts
> +      expect(
oh this kind of stuff gonna be broken when new filter format is merged. lol

2022-08-25 11:04 UTC, ratik commented on src/testcases/interchain_kv_query.test.ts
> +    //       because we only have one node per network in cosmopark
can you just create a task about it so we can decide on planning wether we do it or not

2022-08-25 11:08 UTC, ratik commented on src/testcases/interchain_kv_query.test.ts
> +    test('perform icq #4: transfers', async () => {
You can for sure modify contract the way it helps you test the scope of the task but keep backward compatibility if possible (so you don't have to fix bash test too)

2022-08-25 11:30 UTC, foxpy commented on src/testcases/interchain_kv_query.test.ts
> +      expect(
Can I do something about it or is it better to just leave things as is?

2022-08-25 11:39 UTC, sotnikov-s commented on src/testcases/interchain_kv_query.test.ts
> +      expect(
just wait and adapt. so do I

2022-08-25 18:31 UTC, ratik commented on src/testcases/interchain_kv_query.test.ts
> +      expect(
ok, it's in master

2022-08-25 18:51 UTC, foxpy commented on src/testcases/interchain_kv_query.test.ts
> +      expect(
fixed!

2022-08-25 21:32 UTC, foxpy commented on src/testcases/interchain_kv_query.test.ts
> +    test('perform icq #4: transfers', async () => {
okay, I guess now I have implemented this part as well

2022-08-25 21:47 UTC, foxpy commented on src/testcases/interchain_kv_query.test.ts
> +    //       because we only have one node per network in cosmopark
[Done](https://p2pvalidator.atlassian.net/browse/LSC-163)

2022-08-26 06:10 UTC, ratik approved these changes

2022-08-26 07:20 UTC, oopcode approved these changes

2022-08-26 07:20 UTC, oopcode commented
tested, everything seems to work fine

2022-08-29 05:50 UTC, foxpy commented on src/testcases/interchain_kv_query.test.ts
> +  });
This test doesn't work anymore. Transfer never arrives again, I guess that's expected behaviour for a stateful relayer?

2022-08-29 05:53 UTC, foxpy commented on src/testcases/interchain_kv_query.test.ts
> +  });
@quasisamurai please leave your opinion here.

context: tx query result arrives, but contract callback handler fails. tx query used to arrive again (in other words, callback was executed again), but it doesn't anymore.

2022-08-29 07:38 UTC, foxpy commented on src/testcases/interchain_kv_query.test.ts
> +  });
This new behaviour is correct, because currently relayer stops submitting tx query results after a failure. The only time when retransmit should happen is when there is network error (still unimplemented).

I should update test accordingly.

2022-08-29 07:38 UTC, quasisamurai commented on src/testcases/interchain_kv_query.test.ts
> +  });
if I understand this correct - this is expected. now we are dropping duplicated txs, even if they're failed

2022-08-29 07:48 UTC, quasisamurai requested changes
Please consider update test `Test 'tx' interchain query rollback` with new relayer's behavior: now duplicated (by `queryID` + `txHash`) txs are dropped

2022-08-30 07:38 UTC, quasisamurai commented
tested. works nice

2022-08-30 07:39 UTC, quasisamurai approved these changes

2022-08-30 08:39 UTC, foxpy commented
Will undraft after refactoring

2022-08-30 15:19 UTC, sotnikov-s approved these changes

2022-08-31 07:18 UTC, merged