Update our tokenfactory to the latest version NTRN-93
neutron-org/neutron-integration-tests pull request #200
Opened 2023-09-08 08:59 UTC by quasisamurai

2023-09-12 07:03 UTC, sotnikov-s requested changes

2023-09-12 07:03 UTC, sotnikov-s commented on src/testcases/parallel/governance.test.ts
> +        'Update interchaintxs params',
what about other modules? I'd like to make sure we didn't miss a thing in the copy+paste exercise

2023-09-13 14:12 UTC, quasisamurai commented on src/testcases/parallel/governance.test.ts
> +        'Update interchaintxs params',
we discussed it on refinement

2023-09-14 05:59 UTC, quasisamurai commented
https://github.com/neutron-org/neutron-tests/actions/runs/6173587028/job/16762188644

2023-09-14 08:58 UTC, quasisamurai commented on src/testcases/parallel/tokenfactory.test.ts
> +      expect(res.cosm_wasm_addr).toEqual(contractAddress);
I'd like too, but it's gonna require implementation of the whole contract w custom logic (and we don't want to waste any more time). so:

1. code of whole module is copypasted
2. module integrated successfully
3. the test will be more about contract written for this test
4. time pressure

2023-09-14 08:59 UTC, quasisamurai commented on src/testcases/parallel/governance.test.ts
> +      await daoMember1.executeProposalWithAttempts(proposalId);
done

2023-09-15 14:50 UTC, quasisamurai commented
https://github.com/neutron-org/neutron-tests/actions/runs/6173587028

2023-09-17 14:01 UTC, quasisamurai commented
https://github.com/neutron-org/neutron-tests/actions/runs/6173587028

2023-09-18 10:09 UTC, NeverHappened requested changes

2023-09-18 10:09 UTC, NeverHappened commented on src/testcases/parallel/tokenfactory.test.ts
> +      console.log(queryBlock);
console.log

2023-09-18 10:09 UTC, NeverHappened commented on src/testcases/parallel/tokenfactory.test.ts
> +      console.log(queryTrack);
console.log

2023-09-18 10:09 UTC, NeverHappened commented on src/testcases/parallel/tokenfactory.test.ts
> +      let queryBlock = await neutronChain.queryContract<{
`queryBlock` is never checked actually

2023-09-18 10:09 UTC, NeverHappened commented on src/testcases/parallel/tokenfactory.test.ts
> +      let queryTrack = await neutronChain.queryContract<{
same: please check what's there

2023-09-19 20:44 UTC, quasisamurai commented
https://github.com/neutron-org/neutron-tests/actions/runs/6173587028/job/16939576523 actually test are passing

2023-09-20 00:00 UTC, NeverHappened commented
yeah, I have last tests passing now https://github.com/neutron-org/neutron-tests/actions/runs/6238607927

2023-09-20 10:24 UTC, sotnikov-s approved these changes

2023-09-20 12:25 UTC, merged