add sdk-47 params test NTRN-113
neutron-org/neutron-integration-tests pull request #223
Opened 2023-10-16 11:39 UTC by quasisamurai

[TASK](https://hadronlabs.atlassian.net/browse/NTRN-113)

2023-10-16 17:26 UTC, quasisamurai commented
https://github.com/neutron-org/neutron-tests/actions/runs/6533928970/job/17747811926

2023-10-17 07:33 UTC, pr0n00gler approved these changes

2023-10-24 10:18 UTC, sotnikov-s requested changes

2023-10-24 10:18 UTC, sotnikov-s commented on src/testcases/run_in_band/parameters.test.ts
> +    test('create proposal #1, will pass', async () => {
apparently you've used some parts from governance test code to create this one. there was a point in phrases like "create proposal **#1, will pass**", and "create several proposals", but in this test file it's rather confusing: it's not just several proposals, it's proposals serving concrete goal, and they all pass as far as I can see, we don't test passed/failed proposal logic here. so it would be much clean if there will only be descriptions related to this very test file, no more no less. please consider:
1. cleaning up the file from ambiguous descriptions
2. giving test suites more meaningful names e.g. `create proposal #1, will pass` -> `create param change proposal for interchainqueries`. same below where you execute proposals

2023-10-24 10:18 UTC, sotnikov-s commented on src/testcases/run_in_band/parameters.test.ts
> +    test('create proposal #1, will pass', async () => {
additionally, since it's not a gov test, but params update test, another simplification that you can apply is reducing the number of dao members to 1. this would 1) shorten code 2) remove confusion around YES NO YES votes 3) reduce test run time

2023-10-24 10:18 UTC, sotnikov-s commented on src/testcases/run_in_band/parameters.test.ts
> +    });
this is kind of annoying — to compare results from this part of the code with the ones in the proposal above: one should look here, memorise values, scroll above, compare, and do all these 7 times for each module. would be much better to have test for a module placed as a whole between other modules' test cases, e.g.

icq module proposal created, voted for, executed, checked, then the same for tokenfactory, and so on

2023-10-24 10:18 UTC, sotnikov-s commented on src/testcases/run_in_band/parameters.test.ts
> +    });
another idea is to move these new parameters to constants and reuse them in both proposal creation and in assertions

2023-10-24 10:18 UTC, sotnikov-s commented on src/testcases/run_in_band/parameters.test.ts
> +      expect(params.params.denom_creation_gas_consume).toEqual('100000');
how do we make sure these new values are actually not the same as the old ones? e.g. if we ever change the neutron tokenfactory genesis to have `denom_creation_fee=0` and `denom_creation_gas_consume= 100000`, we won't notice a possible bug because this test won't work properly. please add checks all over the test file that new params are not the same as old params

2023-10-30 12:06 UTC, NeverHappened requested changes

2023-10-30 12:06 UTC, NeverHappened commented on src/testcases/run_in_band/parameters.test.ts
> +    });
Agree with above - how about really to create tests, in which each test would go through complete cycle?
Link this:
- save previous param values
- create proposal
- vote for it (can be one dao member as mentioned above)
- execute it
- check new param values are different from the old ones

2023-10-31 12:27 UTC, NeverHappened approved these changes

2023-11-02 08:36 UTC, sotnikov-s requested changes
besides the new comments, I still see a number of misprints/ambiguities/unaccounted comments from the previous time

2023-11-02 08:36 UTC, sotnikov-s commented on src/testcases/run_in_band/parameters.test.ts
> +    });
what's the point of using a complicated func like getWithAttempts here? it makes sense to use it in async/await flows like interchain transactions where we don't know for sure when the result comes. here it's enough to just wait a block and make a simple query — results should be available straight after the pause. yeah it doesn't really matter here in terms of pros but a most obvious con here is the error case: if there's an error, we won't make 20 tries waiting for a success result, but fail immediately

2023-11-02 08:36 UTC, sotnikov-s commented on src/testcases/run_in_band/parameters.test.ts
> +      const proposalId = 3;
how do you find an idea of introducing proposals counter like `lastProposalId` which will be incremented each time you make a proposal and reused as is instead of hardcoded digits? like that, it will be easily possible to rearrange tests and add more to the middle just with a simple copy+paste. it will also reduce the hardcode part. just an idea very much unnecessary to be implemented, totally up to you

2023-11-02 08:39 UTC, quasisamurai commented on src/testcases/run_in_band/parameters.test.ts
> +        // "fee_collector_address":"neutron1suhgf5svhu4usrurvxzlgn54ksxmn8gljarjtxqnapv8kjnp4nrstdxvff"}}
Default params are defined at `params.go`. This comment purpose is just to make test more clear when you read it

2023-11-02 08:44 UTC, quasisamurai commented on src/testcases/run_in_band/parameters.test.ts
> +      const proposalId = 3;
Purpose of this test is to make sure that it is possible to update params via governance, so i don't think it would make any sense (until we change the whole idea of this test suit) to rearrange order/insert smth in the middle. But idea w non-hardcoded `id` is pretty nice, i'll add it.

2023-11-02 08:47 UTC, quasisamurai commented on src/testcases/run_in_band/parameters.test.ts
> +    });
This is just a common way how we call this type of funcs (e.g. exaclty same way is `subdao/gov` test suits. I personally  don't see any issue w that

2023-11-03 12:56 UTC, quasisamurai commented
https://github.com/neutron-org/neutron-tests/actions/runs/6533928970

2023-11-08 13:11 UTC, sotnikov-s approved these changes

2023-11-08 13:46 UTC, merged