feat: LIDO-68. Signing info query
neutron-org/neutron-integration-tests pull request #257
Opened 2024-01-11 16:20 UTC by albertandrejev

Add support for the signing info queries.

Depends on:
- https://github.com/neutron-org/neutron-dev-contracts/pull/38
- https://github.com/neutron-org/neutron-sdk/pull/122
- https://github.com/neutron-org/neutronjsplus/pull/19

[Test run](https://github.com/neutron-org/neutron-tests/actions/runs/7801343130)

2024-01-14 21:38 UTC, pr0n00gler requested changes
There are no tests for unbonding delegation, please add it

2024-01-14 21:38 UTC, pr0n00gler commented on src/testcases/run_in_band/interchain_kv_query.test.ts
> +      console.log(interchainQueryResult);
I don't think this test actually tests anything, it just prints something in a console

2024-01-15 09:21 UTC, albertandrejev commented
> There are no tests for unbonding delegation, please add it

@foxpy

2024-02-05 21:59 UTC, foxpy commented
https://github.com/neutron-org/neutron-tests/actions/runs/7791362663

2024-02-06 13:58 UTC, foxpy commented
https://github.com/neutron-org/neutron-tests/actions/runs/7800817423

2024-02-12 14:57 UTC, pr0n00gler approved these changes

2024-02-12 14:59 UTC, pr0n00gler commented on src/testcases/run_in_band/interchain_kv_query.test.ts
> +      // XXX: I could actually check that "key" is correctly derived from contractAddress,
I don't think we need this here, if it's covered in SDK unit-tests

2024-02-13 15:39 UTC, pr0n00gler approved these changes

2024-02-20 13:31 UTC, quasisamurai approved these changes

2024-02-22 13:05 UTC, merged