Add proposal votes tests
neutron-org/neutron-integration-tests pull request #265
Opened 2024-02-07 18:25 UTC by albertandrejev

2024-04-10 08:27 UTC, albertandrejev commented
https://github.com/neutron-org/neutron-tests/actions/runs/8597409604

2024-04-10 11:43 UTC, sotnikov-s requested changes

2024-04-10 11:43 UTC, sotnikov-s commented on src/testcases/run_in_band/interchain_kv_query.test.ts
> +          'cosmos1fku9gl93dy3z4d2y58gza06un72ulmd8trruxw',
if I get it right, the second address is a random address that doesn't vote on this proposal. could you please add a note about it? also the `{ proposal_id: 0, voter: '', options: [] }` in the `expect` call below might be unclear, please add some comment describing it as well

2024-04-10 11:43 UTC, sotnikov-s commented on src/testcases/run_in_band/interchain_kv_query.test.ts
> +      );
we provide a parameter to specify voters for `registerProposalVotesQuery`, and it would be nice to test that this kind of filter works. for example, we could have gaia1 and gaia2 addresses that have voted for a proposal and only one of them in the respective ICQ, and in this scenario we would expect only one address presented in the ICQ result

2024-04-10 11:43 UTC, sotnikov-s commented on src/testcases/run_in_band/interchain_kv_query.test.ts
> +        [proposalId, proposalId + 1, proposalId + 2],
same here: please briefly describe the `proposalId + 1, proposalId + 2` and empty results below

2024-04-10 11:43 UTC, sotnikov-s commented on src/helpers/gaia.ts
> +  console.log('msgVote', voter, proposalId, amount);
please remove all console.log calls

2024-04-11 08:58 UTC, sotnikov-s approved these changes

2024-04-11 11:14 UTC, pr0n00gler approved these changes

2024-04-11 11:14 UTC, merged