feat: flashloans
neutron-org/neutron-integration-tests pull request #304
Opened 2024-06-07 05:24 UTC by zavgorodnii

This PR adds tests for the `neutron-flashloans` contract (https://github.com/neutron-org/neutron-dao/pull/105).

2024-06-21 13:16 UTC, NeverHappened requested changes
How about finding some way to test if those funds can actually be used in the moment of the loan? I feel that checking only for the end balance of DAO is not really checking that flashloans work

2024-06-27 09:05 UTC, sotnikov-s requested changes

2024-11-12 13:22 UTC, zavgorodnii commented on src/testcases/run_in_band/flashloans.test.ts
> +      expiration.setDate(expiration.getDate() + 1);
removed expiration, thanks

2024-11-12 13:35 UTC, zavgorodnii commented on src/testcases/run_in_band/flashloans.test.ts
> +              execution_mode: 3, // MODE_WITHHOLD_LOAN
fixed

2024-11-16 06:09 UTC, sotnikov-s approved these changes

2026-04-08 11:51 UTC, closed without merging