feat: whitelist tf hooks
neutron-org/neutron-integration-tests pull request #314
Opened 2024-06-20 07:20 UTC by jcompagni10

for https://github.com/neutron-org/neutron/pull/587

2024-06-21 09:07 UTC, sotnikov-s approved these changes

2024-07-01 13:24 UTC, pr0n00gler submitted a review, later dismissed

2024-07-01 14:59 UTC, sotnikov-s requested changes

2024-07-01 14:59 UTC, sotnikov-s commented on src/testcases/parallel/tokenfactory.test.ts
> +    'Proposal #2',
given the fact you call this func several times, it's incorrect (and doesn't actually have any point to do so) to set the `#2` number to the proposal in the title

2024-07-01 14:59 UTC, sotnikov-s commented on src/testcases/parallel/tokenfactory.test.ts
> +    'Cron update params proposal. Will pass',
it's not cron params update proposal. please give your changes a thorough look in the context of the change when copy+pasting

2024-07-01 16:44 UTC, jcompagni10 commented
https://github.com/neutron-org/neutron-tests/actions/runs/9670374932

2024-07-01 17:57 UTC, sotnikov-s reviewed
excuse me, one more thing. please add a test that asserts that hooks fail if not whitelisted

2024-07-02 09:34 UTC, sotnikov-s requested changes

2024-07-02 09:34 UTC, sotnikov-s commented on src/testcases/parallel/tokenfactory.test.ts
> +        expect(res.code).not.toEqual(0); // set hook fails
would be more accurate to check that the exact error is returned, not that just something went wrong

2024-07-03 07:34 UTC, sotnikov-s commented on src/testcases/parallel/tokenfactory.test.ts
> +      expect(res2.code).toEqual(14); // "beforeSendHook is not whitelisted"
it's good enough to check the code, but just FYI for the future: a more convenient IMO way to check errors is by the error message e.g. like here (or actually in many other places in our tests) https://github.com/neutron-org/neutron-integration-tests/blob/601f0614b1c5e57dc7c75f91b4e20701fc4527ca/src/testcases/run_in_band/tge.auction.test.ts#L1977-L1988

2024-07-03 07:46 UTC, sotnikov-s commented on src/testcases/parallel/tokenfactory.test.ts
> +  expect(timelockedProp.status).toEqual('executed');
didn't this (speeded up?) approach work? I can see that you added it and then removed in the latest commits
<img width="656" alt="image" src="https://github.com/neutron-org/neutron-integration-tests/assets/34917380/86b587e2-8fff-4496-8eba-f36586b9fd78">

2024-07-03 07:46 UTC, sotnikov-s submitted a review, later dismissed
comments above are only informative, so approving it

2024-07-03 17:43 UTC, jcompagni10 commented on src/testcases/parallel/tokenfactory.test.ts
> +      expect(res2.code).toEqual(14); // "beforeSendHook is not whitelisted"
could be mistaken but the way `msgSetBeforeSendHook` is called I can't use `rejects`

2024-07-04 16:09 UTC, merged