Feat: Whitelist tokenfactory hooks (disable tests only)
neutron-org/neutron-integration-tests pull request #316
Opened 2024-06-21 04:50 UTC by jcompagni10

Disable setBeforeSendHook tests.

Given the operation overhead of whitelisting, it is unlikely the contracts will be setting BeforeSendHooks.

2024-06-21 16:27 UTC, jcompagni10 commented
test run: https://github.com/neutron-org/neutron-tests/actions/runs/9608462857

2024-06-26 12:34 UTC, pr0n00gler requested changes

2024-06-26 12:34 UTC, pr0n00gler commented on src/testcases/parallel/tokenfactory.test.ts
> +    // test('create denom, set before send hook', async () => {
I think we still need these tests, the only difference - we should create hooks via proposal

2024-06-26 12:55 UTC, swelf19 approved these changes

2024-06-29 22:13 UTC, closed without merging