wip
neutron-org/neutron-integration-tests pull request #32
Opened 2022-11-01 16:22 UTC by ratik

2022-11-07 07:22 UTC, foxpy requested changes
Please update description!

- This PR is part of NTRN-254, not NTRN-250;
- This PR should be merged together with https://github.com/neutron-org/neutron/pull/83 and https://github.com/neutron-org/neutron-contracts/pull/56

2022-11-07 07:23 UTC, foxpy requested changes
Also tests fail for me:
![image](https://user-images.githubusercontent.com/24505352/200249455-4baa76bf-7aa1-4aa1-8a91-2e466f0b3830.png)

2022-11-07 09:47 UTC, foxpy submitted a review, later dismissed

2022-11-07 16:38 UTC, sotnikov-s commented on src/testcases/simple.test.ts
> +          'neutron1mjk79fjjgpplak5wq838w0yd982gzkyf8fxu8u',
please move this addr to a constant with a meaningful name

2022-11-07 16:38 UTC, sotnikov-s commented on src/testcases/simple.test.ts
> +      test('relayer must receive fee', async () => {
what fee does the relayer receive? I thought only error fees are refunded to the relayer

2022-11-07 16:40 UTC, ratik commented on src/testcases/simple.test.ts
> +        expect(balance - 2333 * 2 - relayerBalance).toBeLessThan(5);
sometimes it differs by 1 or 2. I believe it's because of gas spendings

2022-11-07 17:01 UTC, sotnikov-s commented on src/testcases/simple.test.ts
> +      test('relayer must receive fee', async () => {
ah yes, now I see. thank u

2022-11-07 17:01 UTC, sotnikov-s commented on src/testcases/simple.test.ts
> +        expect(balance - 2333 * 2 - relayerBalance).toBeLessThan(5);
could you please add a descriptive comment about it?

2022-11-07 17:07 UTC, sotnikov-s submitted a review, later dismissed

2022-11-07 17:40 UTC, foxpy submitted a review, later dismissed

2022-11-08 08:25 UTC, pr0n00gler approved these changes

2022-11-08 10:06 UTC, sotnikov-s approved these changes

2022-11-08 10:27 UTC, oopcode approved these changes

2022-11-08 10:27 UTC, merged