Take out everything unnecessary from neutronjsplus to integration tests NTRN-336
neutron-org/neutron-integration-tests pull request #326
Opened 2024-07-09 13:41 UTC by quasisamurai

2024-07-30 13:45 UTC, quasisamurai commented
https://github.com/neutron-org/neutron-tests/actions/runs/10103890611/job/28101580019

2024-07-30 15:07 UTC, NeverHappened requested changes

2024-07-30 15:17 UTC, NeverHappened commented on src/testcases/run_in_band/interchain_kv_query.test.ts
> +      );
send tokens two times?

2024-07-31 10:46 UTC, NeverHappened commented
https://github.com/neutron-org/neutron-tests/actions/runs/10177365236

2024-07-31 14:35 UTC, pr0n00gler approved these changes

2024-07-31 15:20 UTC, merged