[WIP] fix tests accordingly to new contract schema
neutron-org/neutron-integration-tests pull request #329
Opened 2024-07-19 14:03 UTC by pr0n00gler

2024-07-31 13:51 UTC, joldie777 commented
Test run: https://github.com/neutron-org/neutron-tests/actions/runs/10176822282

2024-08-05 17:33 UTC, NeverHappened submitted a review, later dismissed

2024-08-06 10:48 UTC, joldie777 submitted a review, later dismissed

2024-08-12 18:43 UTC, joldie777 commented
Test run: https://github.com/neutron-org/neutron-tests/actions/runs/10355673672

2024-08-12 19:44 UTC, NeverHappened requested changes

2024-08-12 19:44 UTC, NeverHappened commented on src/testcases/parallel/grpc_queries.test.ts
> +    test.skip('auth account should work', async () => {
skipped the test? by accident?

2024-08-12 19:44 UTC, NeverHappened commented on yarn.lock
> -"@neutron-org/cosmjs-types@0.9.2-rc1":
can you recreate the yarn.lock? remove it and node_modules folder and run `yarn` again. Since there shouldn't be any changes to yarn.lock

2024-08-12 19:44 UTC, NeverHappened commented on src/testcases/parallel/grpc_queries.test.ts
> +      const res = await querySmart({
can we remove querySmart function in favor of simple calls like in other tests? Just to be consistent everywhere.

2024-08-12 19:44 UTC, NeverHappened commented on package.json
> -}
please return space, linters usually doesn't like when there is not \n at the end of the file

2024-08-13 10:42 UTC, joldie777 commented on src/testcases/parallel/grpc_queries.test.ts
> +    test.skip('auth account should work', async () => {
Nope. This test and 2 more below were skipped intentionally due to an existing [problem](https://github.com/neutron-org/neutron-sdk/blob/4a43e06115fe2768d9fa54c996270eb51694de39/packages/neutron-sdk/src/shim.rs#L178) with serialization of data containing the `@type` field. That's the reason why we can't deserialize the response for now.

2024-08-13 10:42 UTC, joldie777 commented on yarn.lock
> -"@neutron-org/cosmjs-types@0.9.2-rc1":
Done

2024-08-13 10:42 UTC, joldie777 commented on src/testcases/parallel/grpc_queries.test.ts
> +      const res = await querySmart({
Done

2024-08-13 10:42 UTC, joldie777 commented on package.json
> -}
Done

2024-08-13 11:16 UTC, NeverHappened approved these changes

2024-08-13 19:04 UTC, merged