feat: ignore sudo error on ACK
neutron-org/neutron-integration-tests pull request #33
Opened 2022-11-02 15:14 UTC by albertandrejev

In this PR tests solution for the issue https://github.com/neutron-org/neutron/pull/84 from the audit report will be added.

More info: https://p2pvalidator.atlassian.net/browse/NTRN-253

2022-11-03 10:18 UTC, oopcode submitted a review, later dismissed

2022-11-03 10:50 UTC, sotnikov-s requested changes

2022-11-03 10:50 UTC, sotnikov-s commented on src/testcases/interchaintx.test.ts
> +      await waitBlocks(cm1.sdk, 3);
it doesn't seem to be necessary for there is a waiting for it inside the cleanAckResults (in the underlying execTx if to be precise)

2022-11-03 10:50 UTC, sotnikov-s commented on src/testcases/simple.test.ts
> +      await waitBlocks(cm.sdk, 3);
same here about the waiting

2022-11-03 10:50 UTC, sotnikov-s commented on src/testcases/interchaintx.test.ts
> +        (data) => data.failures.length == 2,
I'm having a race condition here: sometimes it passes, sometimes it doesn't with the following error:
```
    expected 2, got 1 : [
      {
        address: 'neutron14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s5c2epq',
        id: '0',
        ack_id: '3',
        ack_type: 'timeout'
      }
    ]
^^^^^^^^^  THIS IS MY console.log('expected 2, got', data.failures.length, ':', data.failures);

    getWithAttempts: no attempts left

      51 |     await waitBlocks(sdk, 1);
      52 |   }
    > 53 |   throw error != null ? error : new Error('getWithAttempts: no attempts left');
         |                                 ^
      54 | };
      55 |

      at getWithAttempts (src/helpers/wait.ts:53:33)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (src/testcases/interchaintx.test.ts:399:33)
```
i.e. it seems like sometimes the sudo failure mock doesn't work. this is true for both cases with the waiting I concerned about and without it

2022-11-03 10:57 UTC, sotnikov-s commented on src/testcases/interchaintx.test.ts
> +        (data) => data.failures.length == 2,
it's also sometimes like this: there is a failure for ack, but no failure for timeout
```
    expected 2, got 1 : [
      {
        address: 'neutron14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s5c2epq',
        id: '0',
        ack_id: '2',
        ack_type: 'ack'
      }
    ]
```

2022-11-03 17:20 UTC, pr0n00gler submitted a review, later dismissed

2022-11-17 09:40 UTC, oopcode approved these changes
tests pass

2022-11-17 10:39 UTC, sotnikov-s approved these changes

2022-11-17 11:21 UTC, merged