Rate limit inttests
neutron-org/neutron-integration-tests pull request #347
Opened 2024-09-10 15:12 UTC by quasisamurai

This is very basic tests for Ibc rate limit module to ensure it works as expected in our environment
[neutronjsplus PR](https://github.com/neutron-org/neutronjsplus/pull/64)

2024-09-19 13:34 UTC, sotnikov-s requested changes

2024-09-19 13:34 UTC, sotnikov-s commented on package.json
> +    "test:rate_limit": "vitest --run src/testcases/run_in_band/rate_limit --bail 1",
let's explicitly specify that this is about IBC rate limiting? here and everywhere across the repo

2024-09-19 13:34 UTC, sotnikov-s commented on setup/hermes/config.toml
> +gas_multiplier = 2.7
why? because of computation increase during packet_recv and packet_send handlers?

2024-09-19 13:34 UTC, sotnikov-s commented on src/helpers/signing_neutron_client.ts
> +export async function CreateWalletFromMnemonic(
why don't use the already existing mnemonicToWallet from helpers/local_state.ts? pretty similar

2024-09-19 13:34 UTC, sotnikov-s commented on src/testcases/parallel/ibc_transfer.test.ts
> +        await waitBlocks(25, gaiaClient);
are you sure that this and several other pause increases are necessary? another tests run duration increase

2024-09-19 13:34 UTC, sotnikov-s commented on src/helpers/signing_neutron_client.ts
> +  console.log('Wallet address:', accounts[0].address);
don't forget to remove debug logs

2024-09-19 13:34 UTC, sotnikov-s commented on src/testcases/parallel/ibc_transfer.test.ts
> +        console.log(failuresResAfter);
more debug logs and operations to remove

2024-09-19 13:36 UTC, quasisamurai commented on setup/hermes/config.toml
> +gas_multiplier = 2.7
yes, otherwise during `ibc_transfer` test contract isn't refunded because of out of gas

2024-09-19 13:36 UTC, quasisamurai commented on src/helpers/signing_neutron_client.ts
> +export async function CreateWalletFromMnemonic(
haven't seen it, thx

2024-09-19 13:37 UTC, quasisamurai commented on src/testcases/parallel/ibc_transfer.test.ts
> +        await waitBlocks(25, gaiaClient);
It seems like yes (i found it last week), but i'll recheck this once again bc nobody likes long testruns

2024-09-24 12:05 UTC, sotnikov-s commented on setup/hermes/config.toml
> +gas_multiplier = 2.7
I wonder if it's got required to increase the multiplier because of a poor simulation process or because the IBC transactions reached the ceiling of `max_gas = 3000000`. if the latter, why don't increase the `max_gas` instead of the multiplier? would be cleaner

2024-09-24 12:39 UTC, sotnikov-s requested changes
would be great to see the following additional test scenarios:
- quota reset, i.e. IBC transfer limits are reset and transfers work again after a quota period is renewed
- multiple quotas of different limits and time spans, i.e. if you have a daily and a weekly quotas of 5 and 10 respectfully, even if a daily quota is reached twice and then renewed, the weekly quota should still prevent transfers
- if the quota is reached by a sender, other senders also cannot make more sends
- IBC transfers made by smart contracts via the ibc-transfer module are also limited

2024-09-24 12:39 UTC, sotnikov-s commented on src/testcases/run_in_band/rate_limit.test.ts
> +        const resBefroreLimit = await gaiaClient.signAndBroadcast(
why do you need an IBC transfer action in a `check that weird IBC denom is uatom indeed` test scope whereas the IBC transfer result is not even used in the check? would be cleaner to split these to two different test scopes e.g.
1. `check that weird IBC denom is uatom indeed`
2. `IBC transfer without any limits` (as above for the outgoing transfer)

2024-09-24 12:39 UTC, sotnikov-s commented on src/testcases/run_in_band/rate_limit.test.ts
> +      // Note: we don't unset the limit afterwards, instead we're removing rate limiting contract from params
would be better to move (and maybe rephrase) the comment to the place you make the removal as an explanation to the removal action

2024-09-24 12:39 UTC, sotnikov-s commented on src/testcases/run_in_band/rate_limit.test.ts
> +      test('IBC transfer to limit', async () => {
the name of the test is not correct

2024-09-24 12:39 UTC, sotnikov-s commented on src/testcases/run_in_band/rate_limit.test.ts
> +        ).toString();
you make a beyond-the-limit transfer while not making a 1%-1 as above. could you please add that good limited case check?

2024-09-24 12:39 UTC, sotnikov-s commented on src/testcases/run_in_band/rate_limit.test.ts
> +                token: { denom: UATOM_IBC_TO_NEUTRON_DENOM, amount: '10' },
given the amount, this IBC send would work even without the rate limiter contract removal since it doesn't go beyond the limit

2024-09-24 12:55 UTC, pr0n00gler commented
> * IBC transfers made by smart contracts via the ibc-transfer module are also limited

This is a very good point.

But i don't think we need to implement others if they are covered in unit-tests in Neutron

2024-09-24 13:01 UTC, quasisamurai commented on src/testcases/run_in_band/rate_limit.test.ts
> +                token: { denom: UATOM_IBC_TO_NEUTRON_DENOM, amount: '10' },
this test is testing a different thing: is that after removal of contract from the state ibc send simply works. it has nothing to do with a limits themselves (because rate-limiting MW action is completely removed from the ibc stack)

2024-09-24 13:16 UTC, quasisamurai commented on src/testcases/run_in_band/rate_limit.test.ts
> +        ).toString();
I pesonally don't see any reason to reproduce _an exact_ same test scenario, but for different denom. the logic of that is no different from first test case, so here in order to persuade slight diversity of scenarios we're hitting limit in one tx

2024-09-24 13:20 UTC, quasisamurai commented on src/testcases/run_in_band/rate_limit.test.ts
> +        const resBefroreLimit = await gaiaClient.signAndBroadcast(
split in 2 for better readability

2024-09-24 13:54 UTC, sotnikov-s commented on src/testcases/run_in_band/rate_limit.test.ts
> +        ).toString();
ah, I thought it was an incoming transfer test scenario. alright then, this is fine. but what about an incoming transfer test scenario? I think it makes sense to add one

2024-09-24 13:54 UTC, sotnikov-s commented on src/testcases/run_in_band/rate_limit.test.ts
> +                token: { denom: UATOM_IBC_TO_NEUTRON_DENOM, amount: '10' },
why don't cover two things in a single operation then: not that just IBC transfer works, but that the rate limiting is not applied anymore? by simply removing the contract from the state and making a tiny send you won't be able to know if it's even been removed and is not involved in the IBC middleware stack

2024-09-24 13:55 UTC, sotnikov-s commented on src/testcases/run_in_band/rate_limit.test.ts
> +      test('IBC transfer to limit', async () => {
what does `to limit` mean then if you're overcoming the limit?

2024-10-01 14:35 UTC, sotnikov-s submitted a review, later dismissed
nice!

2024-10-01 14:35 UTC, sotnikov-s commented on src/testcases/run_in_band/ibc_rate_limit.test.ts
> +// These are th
These are th?

2024-10-02 14:29 UTC, pr0n00gler approved these changes

2024-10-02 14:29 UTC, merged