Feat/add tx query test
neutron-org/neutron-integration-tests pull request #4
Opened 2022-08-15 18:25 UTC by sotnikov-s

https://p2pvalidator.atlassian.net/browse/LSC-126

2022-08-15 18:39 UTC, sotnikov-s commented on src/test_contracts/contracts/user_sample/Cargo.toml
> +authors = ["sotnikov-s <sergei.s@p2p.org>"]
what do we want to put here as authors?

2022-08-15 19:30 UTC, pr0n00gler requested changes

2022-08-15 19:30 UTC, pr0n00gler commented on src/test_contracts/contracts/user_sample/Cargo.toml
> +neutron_bindings = {path = "../../../../../neutron-contracts/packages/bindings"}
The repo is already open, so:
```suggestion
interchain_queries = { git = "https://github.com/neutron-org/neutron-contracts", default-features = false, version = "0.1.0"}
neutron_sudo = { git = "https://github.com/neutron-org/neutron-contracts", default-features = false, version = "0.1.0"}
neutron_bindings = { git = "https://github.com/neutron-org/neutron-contracts" }
```

And you don't need an additional mount in the `build_release.sh` script

2022-08-15 19:37 UTC, sotnikov-s commented on src/test_contracts/contracts/user_sample/Cargo.toml
> +neutron_bindings = {path = "../../../../../neutron-contracts/packages/bindings"}
glad to know about it! done

2022-08-15 19:38 UTC, pr0n00gler reviewed
And since we already have `contracts` folder in the root, what do you think of moving all the test-contracts there?

So we can just do `make build` inside `contracts` and all the artifacts will be in one place

2022-08-15 19:38 UTC, pr0n00gler commented on src/helpers/cosmos.ts
> +    const contractsPath = process.env.TEST_CONTRACTS_PATH || './src/test_contracts/artifacts';
What do you think of storing all the artifacts in the root `contracts/artifacts` folder?

2022-08-16 07:59 UTC, foxpy commented on src/helpers/cosmos.ts
> +    const contractsPath = process.env.TEST_CONTRACTS_PATH || './src/test_contracts/artifacts';
`contracts/artifacts` folder is a folder to manually copy artifacts from another repositories to. `src/test_contracts/artifacts` seems to be a folder for contracts which are only used in this repo and only for integration tests.

I personally don't see any problems here.

2022-08-17 12:35 UTC, foxpy commented
@pr0n00gler I guess your threads here are not relevant anymore and can be closed.

2022-08-17 12:43 UTC, sotnikov-s commented on src/helpers/cosmos.ts
> +    const contractsPath = process.env.TEST_CONTRACTS_PATH || './src/test_contracts/artifacts';
we've decided to get rid of the user sample contract in the integration tests repo and work with the neutron-contracts expanding the example contracts for integration tests

2022-08-20 07:30 UTC, ratik commented on src/testcases/interchain_tx_query.test.ts
> +  const sendingToAddr2_1: number = 5000;
maybe
```suggestion
  const amountToAddr1_1: number = 10000;
  const amountToAddr2_1: number = 5000;
```

2022-08-20 07:34 UTC, ratik commented on src/testcases/interchain_tx_query.test.ts
> +  const addr1: string = "neutron1fj6yqrkpw6fmp7f7jhj57dujfpwal4m25dafzx";
do you mind moving this block of vars/consts to the top of describe block? (and similar following ones)

2022-08-20 07:38 UTC, ratik commented on src/helpers/cosmos.ts
> +import { AccAddress } from '@cosmos-client/core/cjs/types';
seems unused

2022-08-22 07:43 UTC, sotnikov-s commented on src/testcases/interchain_tx_query.test.ts
> +  const addr1: string = "neutron1fj6yqrkpw6fmp7f7jhj57dujfpwal4m25dafzx";
they all are used inside other describe scopes below, so no, I can not :)

2022-08-22 12:36 UTC, foxpy commented
Wait, I have missed the part when we have started storing wasm artifacts in this repo. What is the reasoning to do so?

2022-08-22 12:42 UTC, sotnikov-s commented
> Wait, I have missed the part when we have started storing wasm artifacts in this repo. What is the reasoning to do so?

why not? to make the repo ready to use and keep the up to date contracts here, otherwise each of us will have to compile contracts each time he wants to run tests in this or that branch

2022-08-22 19:00 UTC, foxpy commented
> otherwise each of us will have to compile contracts

they are already compiled, you only have to `cp` them.

also, we didn't ship compiled contracts in our previous integration tests framework anyway.

2022-08-23 07:49 UTC, sotnikov-s commented
> > otherwise each of us will have to compile contracts
> 
> they are already compiled, you only have to `cp` them.
> 
> also, we didn't ship compiled contracts in our previous integration tests framework anyway.

yeah, sorry, I meant `copy`. you will have to switch to a possible branch that enhances the contract logic, copy the wasm file to the integration tests repo, etc. I frankly see no meaning in not having up to date contracts here and no harm in having them. you anyway store the latest contract you used in this repo, so why not push it so others will not have to do the copying if any occurred?

2022-08-23 16:35 UTC, foxpy commented
> so why not push it so others will not have to do the copying if any occurred?

Then I at least ask you to store `checksums.txt` as well. It would simplify things further.

2022-08-29 05:04 UTC, foxpy requested changes
Tests are oudated, transactions filter logic has been changed, now you have to fetch `main` in contracts and neutron repos and patch our tests.

2022-08-29 20:06 UTC, pr0n00gler approved these changes

2022-08-30 04:13 UTC, foxpy commented on src/testcases/interchain_tx_query.test.ts
> +      const res = await cm2.msgSend(watchedAddr1, '99999999999999'); // the amount is greater than the sender has
```suggestion
      const res = await cm2.msgSend(watchedAddr1, '99999999999999'); // the amount is greater than the sender has
      expect(res.code).not.toEqual(0);
```

2022-08-30 04:42 UTC, foxpy requested changes
Please apply suggested changes to fix race conditions.

2022-08-30 04:42 UTC, foxpy commented on src/testcases/interchain_tx_query.test.ts
> +      await wait(query1UpdatePeriod * BLOCK_TIME);
```suggestion
      await wait((query1UpdatePeriod + 1) * BLOCK_TIME);
```

2022-08-30 04:42 UTC, foxpy commented on src/testcases/interchain_tx_query.test.ts
> +      await wait(query1UpdatePeriod * BLOCK_TIME);
```suggestion
      await wait((query1UpdatePeriod + 1) * BLOCK_TIME);
```

2022-08-30 04:42 UTC, foxpy commented on src/testcases/interchain_tx_query.test.ts
> +      await wait(query1UpdatePeriod * BLOCK_TIME);
```suggestion
      await wait((query1UpdatePeriod + 1) * BLOCK_TIME);
```

2022-08-30 04:42 UTC, foxpy commented on src/testcases/interchain_tx_query.test.ts
> +      await wait(query2UpdatePeriod * BLOCK_TIME);
```suggestion
      await wait((query2UpdatePeriod + 1) * BLOCK_TIME);
```

2022-08-30 04:42 UTC, foxpy commented on src/testcases/interchain_tx_query.test.ts
> +      await wait(query3UpdatePeriod * BLOCK_TIME);
```suggestion
      await wait((query3UpdatePeriod + 1) * BLOCK_TIME);
```

2022-08-30 04:42 UTC, foxpy commented on src/testcases/interchain_tx_query.test.ts
> +      await wait(query3UpdatePeriod * BLOCK_TIME);
```suggestion
      await wait((query3UpdatePeriod + 1) * BLOCK_TIME);
```

2022-08-30 04:42 UTC, foxpy commented on src/testcases/interchain_tx_query.test.ts
> +        Math.max(query1UpdatePeriod, query2UpdatePeriod, query3UpdatePeriod) *
```suggestion
        (Math.max(query1UpdatePeriod, query2UpdatePeriod, query3UpdatePeriod) +
          1) *
```

2022-08-30 04:42 UTC, foxpy commented on src/testcases/interchain_tx_query.test.ts
> +      await wait(query4UpdatePeriod * BLOCK_TIME);
```suggestion
      await wait((query4UpdatePeriod + 1) * BLOCK_TIME);
```

2022-08-30 04:42 UTC, foxpy commented on src/testcases/interchain_tx_query.test.ts
> +      await wait(query5UpdatePeriod * BLOCK_TIME);
```suggestion
      await wait((query5UpdatePeriod + 1) * BLOCK_TIME);
```

2022-08-30 13:59 UTC, foxpy submitted a review, later dismissed
Apparently, the aforementioned race conditions are only reproducible on my machine (?). As much as I would love to see them fixed (it is enough just to apply my suggestions), I am approving this PR to prevent further review delays.

2022-08-30 15:03 UTC, sotnikov-s commented
> Apparently, the aforementioned race conditions are only reproducible on my machine (?). As much as I would love to see them fixed (it is enough just to apply my suggestions), I am approving this PR to prevent further review delays.

I've run the tests 25+ times and haven't encountered any race condition. Race conditions ceased to be my problem since stateful relayer came into play. But anyway I appreciate your request and I've increased the pause duration as you suggested. Please take a look now

2022-08-30 15:27 UTC, foxpy commented
After extensive testing I have discovered these fixes don't work :|

They just make fails more rare.

2022-08-30 15:27 UTC, foxpy approved these changes
Anyway, approving this as it is

2022-08-31 13:37 UTC, foxpy approved these changes

2022-09-01 08:14 UTC, merged