feat: NTRN-260 resubmit failed txs test
neutron-org/neutron-integration-tests pull request #40
Opened 2022-11-22 07:16 UTC by swelf19

test case for "resubmit failed tx" functionality

https://github.com/neutron-org/neutron-query-relayer/pull/65

contracts from pr https://github.com/neutron-org/neutron-contracts/pull/68 are required

2022-12-06 15:52 UTC, foxpy requested changes

2022-12-06 15:52 UTC, foxpy commented on src/helpers/env.ts
> +  }
Please document this new variable in README.

2022-12-06 16:22 UTC, sotnikov-s requested changes

2022-12-08 11:06 UTC, foxpy approved these changes

2022-12-14 08:37 UTC, sotnikov-s reviewed
tested: everything works. the only thing I'd like to see before I approve is the detailed error `resubmit nonexistent failed tx` instead of uninformative `Request failed with status code 400`

2022-12-14 11:21 UTC, sotnikov-s approved these changes

2022-12-14 12:29 UTC, sotnikov-s approved these changes

2022-12-15 09:51 UTC, merged