feat: NTRN-267. ICQ removal after timeout
neutron-org/neutron-integration-tests pull request #42
Opened 2022-11-24 22:18 UTC by albertandrejev

**Summary**

It is possible by anyone to delete ICQ after submission timeout and receive deposit from it. We need tests for this behavior.

**DoD**

Following test cases should be implemented:

- attempt to delete ICQ before submission timeout should fail;
- attempt to delete ICQ after submission timeout should succeed (and funds should be returned);
- change of timeout via governance should be reflected (in case if it is impossible to use governance in current integration tests, TODO comment should be left);
- change of deposit should be reflected, it is especially important to check that the whole deposit is always being returned (in case if it is impossible to use governance in current integration tests, TODO comment should be left).

**Related PRs**
https://github.com/neutron-org/neutron/pull/95

2022-12-12 12:28 UTC, oopcode approved these changes

2022-12-12 13:55 UTC, ratik commented on .gitignore
> -*.wasm
are we going to store binaries again?

2022-12-12 14:07 UTC, albertandrejev commented on .gitignore
> -*.wasm
only for DAO contracts

2022-12-14 08:40 UTC, foxpy commented on .gitignore
> -*.wasm
please don't :crying_cat_face:

2022-12-14 08:44 UTC, albertandrejev commented on .gitignore
> -*.wasm
Yes, it should move to the meta-repo. Let's see

2022-12-18 15:44 UTC, foxpy requested changes

2022-12-18 15:44 UTC, foxpy commented on src/testcases/interchain_kv_query.test.ts
> +  );*/
Wait, why is it commented out? I see you wanted to wait for actual proposal approval, but instead you just wait for N blocks to pass. Please remove fixed sleeps and wait until proposal is accepted.

2022-12-18 21:57 UTC, albertandrejev commented on src/testcases/interchain_kv_query.test.ts
> +  );*/
fixed

2022-12-23 02:02 UTC, foxpy reviewed
As much as I would like to approve it, two last tests in KV query test suite are failing.

2022-12-23 09:27 UTC, albertandrejev commented
> As much as I would like to approve it, two last tests in KV query test suite are failing.

Yes, I know. I said about it in my message. I believe these tests should be fixed in the https://github.com/neutron-org/neutron-integration-tests/pull/51
This happens because of incompatibility in the old DAO contracts the last changes in neutron.

2022-12-23 09:41 UTC, foxpy approved these changes
Let's get it merged for now

2022-12-23 09:45 UTC, quasisamurai approved these changes
tested ack

2022-12-23 09:56 UTC, merged