feat: Implement burn-based vesting for treasury. NTRN-308
neutron-org/neutron-integration-tests pull request #53
Opened 2022-12-23 18:53 UTC by albertandrejev

Treasury tokens are vested based on on-chain activity: burnt_tokens * a_multiplier. The multiplier is an linear function of the supply: while initially, one burnt tokens equals multiple NTRN tokens made liquid, the flow of new tokens into the Treasury progressively slows down until the tokens supply is exhausted and the tokenomy becomes deflationary.

Depends on https://github.com/neutron-org/neutron-dao/pull/15

2023-01-11 08:46 UTC, sotnikov-s requested changes

2023-01-11 08:46 UTC, sotnikov-s commented on src/testcases/treasury.test.ts
> +        expect(stats.total_processed_burned_coins).toEqual(burnedCoins);
we test here whether stats' processed burned coins can properly follow the burned coins amount taken from neutron, right? and we assume that with each `executeContract(distribute)` new coins get burned, so this is why the test is named `burned coins increment`. if I get it right, it would be good to also test whether `burnedCoins` increases between calls

2023-01-11 08:46 UTC, sotnikov-s commented on src/testcases/treasury.test.ts
> +        // treasury = await setupTreasury(cm, {
can be removed

2023-01-11 08:46 UTC, sotnikov-s commented on src/testcases/treasury.test.ts
> +        // treasury = await setupTreasury(cm, {
can be removed

2023-01-11 08:46 UTC, sotnikov-s commented on src/testcases/treasury.test.ts
> +        await cm.simulateFeeBurning(4_294_967_295);
but it's not an overflow

2023-01-11 08:46 UTC, sotnikov-s commented on src/testcases/treasury.test.ts
> +              158050 + parseInt(treasuryStats.total_reserved)
could you please describe these magic numbers somehow? if things go the way the test fails here, it will be complicated to understand why we expect here exactly these values

2023-01-11 14:56 UTC, foxpy commented on src/helpers/cosmos.ts
> +        `${this.sdk.url}/neutron/feeburner/totalburnedneutronsamount`,
the path has changed:
```suggestion
        `${this.sdk.url}/neutron/feeburner/total_burned_neutrons_amount`,
```

2023-01-13 13:24 UTC, albertandrejev commented on src/testcases/treasury.test.ts
> +        await cm.simulateFeeBurning(4_294_967_295);
agree, wrong test name, it checks `safe_burned_coins_for_period` function in the contract.

2023-01-13 13:28 UTC, albertandrejev commented on src/testcases/treasury.test.ts
> +        expect(stats.total_processed_burned_coins).toEqual(burnedCoins);
No, because of u32 limitations we can not process more then u32::MAX burned coins at a time. So we we have burned more then u32::MAX coins then we need to call contract at least two times to process all burned coins. See https://github.com/neutron-org/neutron-dao/blob/306c06e1b39e90b6a1d41ee114a32b6b751b7a37/contracts/tokenomics/treasury/src/vesting.rs#L35

2023-01-13 13:52 UTC, albertandrejev commented on src/testcases/treasury.test.ts
> +        expect(stats.total_processed_burned_coins).toEqual(burnedCoins);
wrong answer :point_up: , mixed up it with `burned coins amount u32 safe calculation` test.

2023-01-13 13:59 UTC, albertandrejev commented on src/testcases/treasury.test.ts
> +        expect(stats.total_processed_burned_coins).toEqual(burnedCoins);
It was implemented, see line 91

2023-01-13 18:04 UTC, merged