fix: remove eslint + remove some any
neutron-org/neutron-integration-tests pull request #61
Opened 2023-01-12 11:56 UTC by ratik

2023-01-12 12:18 UTC, sotnikov-s approved these changes

2023-01-12 12:41 UTC, foxpy requested changes

2023-01-12 13:02 UTC, ratik commented on src/helpers/wait.ts
> +export const waitBlocks = async (sdk: CosmosSDK, n: number) => {
fixed

2023-01-12 14:53 UTC, sotnikov-s submitted a review, later dismissed

2023-01-12 14:59 UTC, sotnikov-s submitted a review, later dismissed

2023-01-12 16:01 UTC, albertandrejev commented on src/testcases/interchaintx.test.ts
> +        let rawLog: string;
btw, please replace `expect` call below with something similar to `expect(rawLog).stringContaining('no active channel for this owner')`

2023-01-12 20:05 UTC, ratik commented on src/testcases/interchaintx.test.ts
> +        let rawLog: string;
So this way you'll have to `expect(rawLog || '').stringContaining('no active channel for this owner')` as `stringContaining` accepts string only. Let's leave it as it is

2023-01-17 10:49 UTC, albertandrejev submitted a review, later dismissed

2023-01-17 10:50 UTC, NeverHappened requested changes

2023-01-17 10:50 UTC, NeverHappened commented on src/helpers/cosmos.ts
> +    core_contract: string,
can we change all arguments in cosmos.ts to camelCase? I've also seen `propose_contract` arg.

2023-01-17 10:52 UTC, foxpy approved these changes

2023-01-17 10:54 UTC, ratik commented on src/helpers/cosmos.ts
> +    core_contract: string,
but actually this one is out of scope of this pr. will do one more

2023-01-17 11:00 UTC, albertandrejev submitted a review, later dismissed

2023-01-17 11:03 UTC, NeverHappened submitted a review, later dismissed

2023-01-17 11:11 UTC, foxpy approved these changes
utACK

2023-01-18 12:33 UTC, foxpy requested changes
Requesting changes because this looks very bad.

2023-01-18 12:33 UTC, foxpy commented on src/helpers/cosmos.ts
> +      this.sdk,
whaaat, how does it work if this function accepts `CosmosWrapper`, not `CosmosSDK`????

2023-01-19 10:34 UTC, ratik commented on src/helpers/cosmos.ts
> +      this.sdk,
can't remember it 🤡
but the idea looks nice

2023-01-19 12:57 UTC, foxpy approved these changes
Looks good

2023-01-19 13:30 UTC, oopcode approved these changes

2023-01-19 13:31 UTC, merged