feat: tests for timeout logic and reopening ICA channel
neutron-org/neutron-integration-tests pull request #7
Opened 2022-08-26 12:10 UTC by pr0n00gler

**Task**: https://p2pvalidator.atlassian.net/jira/software/projects/LSC/boards/121?selectedIssue=LSC-152 + https://p2pvalidator.atlassian.net/jira/software/projects/LSC/boards/121?selectedIssue=LSC-129

What tests are implemented:
* custom timeout when submitting ICA tx;
* tests for reregistering ICA after it was closed by timeout.

**Test with**: 
* https://github.com/neutron-org/neutron-contracts/pull/20 
* https://github.com/neutron-org/neutron/pull/43

2022-08-29 14:12 UTC, foxpy requested changes

2022-08-29 14:12 UTC, foxpy commented on src/helpers/cosmos.ts
> -    }
Hey, deleting this code degrades quality of other tests since they will no longer ensure correct contract execution.

I suggest you bringing these lines of code back and using `try { /* snip */ } catch (e) { expect(e).toWhatever(); }` everywhere you expect contract to fail.

2022-08-29 14:24 UTC, pr0n00gler commented on src/helpers/cosmos.ts
> -    }
We explicitly check everywhere that tx was executed successfully: (CTRL + F: `expect(res.code).toEqual(0); `)

I've removed the code above because I need to check that I get error which I expect. The removed code does not allow it.

2022-08-29 14:27 UTC, foxpy commented on src/helpers/cosmos.ts
> -    }
Yeah, but we also have two other PRs which we will have to modify, too, and they have quite a lot of code and I am not happy about it.

You are free to resolve this thread and I will approve your PR, but this part I really don't like.

2022-08-29 14:48 UTC, pr0n00gler commented on src/helpers/cosmos.ts
> -    }
I don't like the idea with `try catch` only because we will need to add additional explicit one-line checks in other PRs.

Anyway I'm 100% sure those PR's will be merged before mine, so the person who will need to add the checks will be me obviously.

2022-08-29 14:49 UTC, foxpy submitted a review, later dismissed

2022-08-31 06:13 UTC, ratik commented on src/testcases/interchaintx.test.ts
> +          // FIXME: 'stake'
yep. can we get `denom` from `cm2`?

2022-08-31 07:34 UTC, foxpy commented on src/testcases/interchaintx.test.ts
> +          // FIXME: 'stake'
Sure we can, and also under line 145

2022-08-31 12:54 UTC, pr0n00gler commented on src/testcases/interchaintx.test.ts
> +          // FIXME: 'stake'
Don't get you. I thought this comments was about incorrect denom? Like, it should be `neutron`, not `stake`.

@NeverHappened you left such comments there, what did you mean by them?

2022-08-31 13:41 UTC, NeverHappened commented on src/testcases/interchaintx.test.ts
> +          // FIXME: 'stake'
Yeah, I wrote about [this](https://github.com/neutron-org/neutron-integration-tests/pull/7#discussion_r959194326), not about incorrect denom

2022-08-31 13:44 UTC, pr0n00gler commented on src/testcases/interchaintx.test.ts
> +          // FIXME: 'stake'
Okay, guys, clarify please. I still don't understand what you want here

2022-08-31 13:45 UTC, oopcode submitted a review, later dismissed

2022-08-31 13:47 UTC, ratik commented on src/testcases/interchaintx.test.ts
> +          // FIXME: 'stake'
just replace 'stake' with  cm2.denom like there https://github.com/neutron-org/neutron-integration-tests/blob/main/src/testcases/simple.test.ts#L55

2022-08-31 13:52 UTC, pr0n00gler commented on src/testcases/interchaintx.test.ts
> +          // FIXME: 'stake'
lol, @NeverHappened, why you didn't do it right away and created a TODO instead :)
I thought there is something incredibly complicated here  🤯

2022-08-31 13:57 UTC, ratik approved these changes

2022-08-31 13:59 UTC, ratik commented on src/testcases/interchaintx.test.ts
>            // FIXME: 'stake'
sorry, so mb remove this misleading comment now?

2022-08-31 14:00 UTC, oopcode approved these changes

2022-08-31 14:02 UTC, oopcode approved these changes

2022-08-31 14:02 UTC, foxpy approved these changes

2022-08-31 14:03 UTC, ratik approved these changes

2022-08-31 14:03 UTC, merged